"""
data.py - Knowledge Base, Employee Requests, and Ticket Queue for Veridian Corp IT Support Agent.
All data is sourced strictly from Assignment 2: Internal Service Agent (IT Support).
"""

# ---------------------------------------------------------------------------
# 1. Knowledge Base / Policies
# ---------------------------------------------------------------------------
POLICIES = {
    "KB-01": {
        "title": "Password Reset",
        "category": "Password Reset",
        "content": (
            "Employees can reset their own password via the self-service portal at any time. "
            "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
            "No approval required."
        ),
        "default_decision": "Resolve / Self-Service",
        "action": "Use self-service portal, or route to IT if locked out after 5 attempts."
    },
    "KB-02": {
        "title": "VPN Access",
        "category": "VPN Access",
        "content": (
            "VPN access is granted automatically to all full-time employees. "
            "Contractors require manager approval submitted via the access request form. "
            "VPN credentials expire every 90 days and must be renewed by the employee."
        ),
        "default_decision": "Resolve / Self-Service",
        "action": "Employee renews credentials every 90 days. Contractors must submit manager approval."
    },
    "KB-03": {
        "title": "Laptop Replacement",
        "category": "Laptop Replacement",
        "content": (
            "Laptops are eligible for replacement after 3 years of service, or earlier in case of "
            "verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
        ),
        "default_decision": "Route to IT",
        "action": "Verify laptop age (3+ years) or hardware failure, raised 2 weeks in advance."
    },
    "KB-04": {
        "title": "Software Installation Requests",
        "category": "Software Installation",
        "content": (
            "Standard software (listed in the approved catalog) can be self-installed. "
            "Non-catalog software requires IT Security review, which takes 3–5 business days."
        ),
        "default_decision": "Security Review Required",
        "action": "Self-install if catalog software; submit for IT Security review if non-catalog."
    },
    "KB-05": {
        "title": "Printer Troubleshooting",
        "category": "Printer Troubleshooting",
        "content": (
            "For printer issues, first check the printer queue and restart the print spooler. "
            "If the issue persists after restart, log a ticket with the printer's asset tag."
        ),
        "default_decision": "Troubleshooting Required",
        "action": "Check printer queue and restart print spooler. Log ticket with asset tag if unresolved."
    },
    "KB-06": {
        "title": "Email Mailbox Quota",
        "category": "Email Mailbox Quota",
        "content": (
            "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. "
            "Quota increases beyond 25GB require manager approval and are capped at 50GB."
        ),
        "default_decision": "Resolve / Self-Service",
        "action": "Archive old mail. If increase is needed beyond 25GB, obtain manager approval (max 50GB)."
    },
    "KB-07": {
        "title": "Guest Wi-Fi Access",
        "category": "Guest Wi-Fi",
        "content": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from "
            "the front-desk kiosk. No IT ticket required."
        ),
        "default_decision": "Resolve / Self-Service",
        "action": "Direct employee or visitor to front-desk kiosk for 24-hour guest credentials. No ticket needed."
    },
    "KB-08": {
        "title": "Expense Software Access",
        "category": "Expense Software Access",
        "content": (
            "Access to the expense management tool is granted by Finance, not IT. "
            "IT can only assist with login/technical issues once an account already exists."
        ),
        "default_decision": "Route to Finance",
        "action": "Contact Finance for account creation. IT assists with technical login only after account exists."
    },
    "KB-09": {
        "title": "Security Incident Reporting",
        "category": "Security Incident",
        "content": (
            "Any suspected phishing email, malware, or unauthorized access attempt must be reported to "
            "security@veridian-corp.example immediately and should not be forwarded to other employees."
        ),
        "default_decision": "Route to Security",
        "action": "Immediately stop forwarding, report to security@veridian-corp.example, and escalate to Security."
    },
    "KB-10": {
        "title": "Work-From-Home Equipment",
        "category": "Work-From-Home Equipment",
        "content": (
            "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment "
            "allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the "
            "equipment shipping request once approved."
        ),
        "default_decision": "Route to Finance",
        "action": "Obtain manager sign-off and Finance processing first. IT will handle shipping after approval."
    },
    "Asset-Policy": {
        "title": "Asset Management Policy (Extract)",
        "category": "Asset Management",
        "content": (
            "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle "
            "from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
        ),
        "default_decision": "Manager Approval Required",
        "action": "Check 4-year refresh cycle. Replacements under 4 years require Finance sign-off plus IT approval."
    }
}

# ---------------------------------------------------------------------------
# 2. Employee Requests (All 15 exactly from the PDF)
# ---------------------------------------------------------------------------
EMPLOYEE_REQUESTS = [
    {
        "request_id": "REQ-01",
        "employee": "Aditi Sharma",
        "email": "aditi.sharma@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request_text": "My laptop won’t turn on at all, it’s completely dead, had it about 3.5 years now.",
        "initial_action": "Not started",
        "category": "Laptop Replacement",
        "relevant_policy": "KB-03 & Asset Management Policy",
        "decision": "Route to IT",
        "recommended_action": "Log replacement request for IT approval and Finance sign-off.",
        "reason": (
            "Laptop is 3.5 years old (>3 years per KB-03) with verified hardware failure. "
            "Because it is under the 4-year standard refresh cycle, Finance sign-off is required "
            "in addition to IT approval per the Asset Management Policy."
        )
    },
    {
        "request_id": "REQ-02",
        "employee": "Vikram Chawla",
        "email": "vikram.chawla@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request_text": "Can I get Wi-Fi access for a guest visiting our office tomorrow?",
        "initial_action": "Not started",
        "category": "Guest Wi-Fi",
        "relevant_policy": "KB-07",
        "decision": "Resolve / Self-Service",
        "recommended_action": "Generate credentials at front-desk kiosk.",
        "reason": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee "
            "from the front-desk kiosk. No IT ticket required."
        )
    },
    {
        "request_id": "REQ-03",
        "employee": "Karan Mehta",
        "email": "karan.mehta@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request_text": "I’m locked out of my account, tried my password 6 times.",
        "initial_action": "In progress — reset queued",
        "category": "Password Reset",
        "relevant_policy": "KB-01",
        "decision": "Route to IT",
        "recommended_action": "IT technician manually unlocks account.",
        "reason": (
            "Employee failed password 6 times (exceeds 5 failed attempts limit). "
            "Self-service reset is unavailable; manual IT unlock is required. No approval needed."
        )
    },
    {
        "request_id": "REQ-04",
        "employee": "Ritu Bhatia",
        "email": "ritu.bhatia@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request_text": "Need approval to install a data-analysis tool that’s not in the software catalog.",
        "initial_action": "Waiting on Security review",
        "category": "Software Installation",
        "relevant_policy": "KB-04",
        "decision": "Security Review Required",
        "recommended_action": "Route request to IT Security review.",
        "reason": (
            "Non-catalog software cannot be self-installed and requires IT Security review, "
            "which takes 3–5 business days."
        )
    },
    {
        "request_id": "REQ-05",
        "employee": "Sanjay Oberoi",
        "email": "sanjay.oberoi@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request_text": "My VPN stopped working this morning, says credentials expired.",
        "initial_action": "Not started",
        "category": "VPN Access",
        "relevant_policy": "KB-02",
        "decision": "Resolve / Self-Service",
        "recommended_action": "Employee renews VPN credentials.",
        "reason": (
            "VPN credentials expire every 90 days and must be renewed by the employee directly. "
            "(Precedent: TK-1042 resolved/closed)."
        )
    },
    {
        "request_id": "REQ-06",
        "employee": "Meera Iyer",
        "email": "meera.iyer@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request_text": "Printer on the 3rd floor keeps showing “paper jam” even though there’s no jam.",
        "initial_action": "Investigating — technician assigned",
        "category": "Printer Troubleshooting",
        "relevant_policy": "KB-05",
        "decision": "Troubleshooting Required",
        "recommended_action": "Clear printer queue and restart print spooler; log ticket with asset tag if unresolved.",
        "reason": (
            "First check printer queue and restart print spooler. If issue persists after restart, "
            "log ticket with the printer's asset tag. Technician has already been assigned."
        )
    },
    {
        "request_id": "REQ-07",
        "employee": "Farhan Ali",
        "email": "farhan.ali@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request_text": "I’ve started working from home 4 days a week, how do I get a monitor?",
        "initial_action": "Not started",
        "category": "Work-From-Home Equipment",
        "relevant_policy": "KB-10",
        "decision": "Route to Finance",
        "recommended_action": "Submit manager sign-off to Finance for allowance processing.",
        "reason": (
            "Working remotely 4 days/week meets the criteria (>3 days/week) for one-time home office allowance. "
            "Requires manager sign-off and Finance processing. IT only handles shipping after approval."
        )
    },
    {
        "request_id": "REQ-08",
        "employee": "Ananya Reddy",
        "email": "ananya.reddy@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request_text": "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.",
        "initial_action": "Escalated to Security (auto-flagged)",
        "category": "Security Incident",
        "relevant_policy": "KB-09",
        "decision": "Route to Security",
        "recommended_action": "Instruct employee to stop forwarding; escalate to security@veridian-corp.example.",
        "reason": (
            "Suspected phishing must be reported immediately to security@veridian-corp.example and "
            "SHOULD NOT be forwarded to other employees. Urgent security risk."
        )
    },
    {
        "request_id": "REQ-09",
        "employee": "Rohit Desai",
        "email": "rohit.desai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request_text": "My mailbox is full and I can’t send emails.",
        "initial_action": "Not started",
        "category": "Email Mailbox Quota",
        "relevant_policy": "KB-06",
        "decision": "Resolve / Self-Service",
        "recommended_action": "Archive old emails. Seek manager approval if quota increase above 25GB is needed.",
        "reason": (
            "Default quota is 25GB. Employees nearing quota should archive old mail. "
            "Increases beyond 25GB require manager approval and are capped at 50GB (Ref: TK-1045)."
        )
    },
    {
        "request_id": "REQ-10",
        "employee": "Kavya Pillai",
        "email": "kavya.pillai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request_text": "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.",
        "initial_action": "Not started",
        "category": "Admin Access",
        "relevant_policy": "KB-08 & Security Policy",
        "decision": "Manager Approval Required",
        "recommended_action": "Submit formal access request with business justification and manager sign-off.",
        "reason": (
            "Admin access to finance reporting servers cannot be granted on verbal request. "
            "Requires formal business justification and manager authorization. "
            "(Precedent: TK-1050 was rejected because no business justification was provided)."
        )
    },
    {
        "request_id": "REQ-11",
        "employee": "Nikhil Bansal",
        "email": "nikhil.bansal@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request_text": "New contractor joining my team next week, they’ll need VPN access.",
        "initial_action": "Not started",
        "category": "VPN Access",
        "relevant_policy": "KB-02",
        "decision": "Manager Approval Required",
        "recommended_action": "Submit contractor access request form with manager approval.",
        "reason": (
            "VPN access is automatic only for full-time employees. "
            "Contractors require manager approval submitted via the access request form."
        )
    },
    {
        "request_id": "REQ-12",
        "employee": "Sneha Kulkarni",
        "email": "sneha.kulkarni@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request_text": "I can’t log into the expense tool, keeps saying invalid credentials.",
        "initial_action": "Waiting on employee response (asked for a screenshot, no reply yet)",
        "category": "Expense Software Access",
        "relevant_policy": "KB-08",
        "decision": "Route to Finance",
        "recommended_action": "Verify account creation with Finance; IT assists with technical login only after account exists.",
        "reason": (
            "Access to the expense management tool is granted by Finance, not IT. "
            "IT can only assist with login/technical issues once an account already exists. "
            "Currently awaiting employee response/screenshot."
        )
    },
    {
        "request_id": "REQ-13",
        "employee": "Aman Gupta",
        "email": "aman.gupta@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request_text": "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.",
        "initial_action": "Not started",
        "category": "Laptop Troubleshooting",
        "relevant_policy": "KB-03 & Asset Management Policy",
        "decision": "Troubleshooting Required",
        "recommended_action": "Route to IT hardware technician for repair and diagnostics.",
        "reason": (
            "Laptop is 2 years old (under the 3-year KB-03 eligibility and 4-year refresh cycle). "
            "Not eligible for scheduled replacement; technician must inspect and repair the screen."
        )
    },
    {
        "request_id": "REQ-14",
        "employee": "Tanya Chopra",
        "email": "tanya.chopra@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request_text": "Requesting approval to install a browser extension for productivity tracking.",
        "initial_action": "Not started",
        "category": "Software Installation",
        "relevant_policy": "KB-04",
        "decision": "Security Review Required",
        "recommended_action": "Submit extension details for IT Security review (takes 3–5 business days).",
        "reason": (
            "Browser extensions not in the approved software catalog require IT Security review, "
            "which takes 3–5 business days."
        )
    },
    {
        "request_id": "REQ-15",
        "employee": "Rahul Menon",
        "email": "rahul.menon@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request_text": "hey can you help, its not working",
        "initial_action": "Not started",
        "category": "Unspecified / General Inquiry",
        "relevant_policy": "N/A (Insufficient Information)",
        "decision": "Ask for More Information",
        "recommended_action": "Request employee to specify device, software, and description of the problem.",
        "reason": (
            "Request is too vague. No device, application, error message, or details were provided. "
            "Clarification is required before the agent can identify the category or policy."
        )
    }
]

# ---------------------------------------------------------------------------
# 3. Ticket Queue (Historical context and active tickets from PDF)
# ---------------------------------------------------------------------------
TICKET_QUEUE = [
    {
        "ticket_id": "TK-1042",
        "employee": "R. Verma",
        "issue_summary": "VPN credential expired",
        "status": "Resolved (closed)",
        "is_active": False,
        "precedent_note": "Direct precedent for KB-02: Employee renewed credentials."
    },
    {
        "ticket_id": "TK-1043",
        "employee": "S. Iyer",
        "issue_summary": "Laptop replacement (3.2 yrs old)",
        "status": "Approved — pending fulfillment (active)",
        "is_active": True,
        "precedent_note": "Active case: Laptop over 3 years old approved, pending dispatch."
    },
    {
        "ticket_id": "TK-1044",
        "employee": "A. Khan",
        "issue_summary": "Non-catalog software request",
        "status": "Pending Security review (active)",
        "is_active": True,
        "precedent_note": "Active case under KB-04: Takes 3–5 business days for Security review."
    },
    {
        "ticket_id": "TK-1045",
        "employee": "P. Joshi",
        "issue_summary": "Mailbox quota increase",
        "status": "Approved at 35GB (closed)",
        "is_active": False,
        "precedent_note": "Direct precedent for KB-06: Quota increase beyond 25GB approved with manager sign-off (within 50GB cap)."
    },
    {
        "ticket_id": "TK-1046",
        "employee": "M. Das",
        "issue_summary": "Printer paper jam, floor 2",
        "status": "Resolved (closed)",
        "is_active": False,
        "precedent_note": "Direct precedent for KB-05: Spooler/queue troubleshooting and physical check."
    },
    {
        "ticket_id": "TK-1047",
        "employee": "K. Singh",
        "issue_summary": "Home office equipment request",
        "status": "Pending Finance (active)",
        "is_active": True,
        "precedent_note": "Active case under KB-10: Manager approved, awaiting Finance processing."
    },
    {
        "ticket_id": "TK-1048",
        "employee": "T. Rao",
        "issue_summary": "Phishing email reported",
        "status": "Escalated to Security — under investigation (active)",
        "is_active": True,
        "precedent_note": "Active incident under KB-09: Phishing reported and contained."
    },
    {
        "ticket_id": "TK-1049",
        "employee": "V. Nambiar",
        "issue_summary": "Password reset",
        "status": "Resolved (closed)",
        "is_active": False,
        "precedent_note": "Direct precedent for KB-01: Password reset successfully completed."
    },
    {
        "ticket_id": "TK-1050",
        "employee": "J. Fernandes",
        "issue_summary": "Admin access request",
        "status": "Rejected — no business justification provided (closed)",
        "is_active": False,
        "precedent_note": "Key precedent for admin/server access: Rejected due to missing business justification."
    },
    {
        "ticket_id": "TK-1051",
        "employee": "L. Menon",
        "issue_summary": "Guest Wi-Fi issued",
        "status": "Resolved (closed)",
        "is_active": False,
        "precedent_note": "Direct precedent for KB-07: Front-desk kiosk issued 24h Wi-Fi pass."
    }
]
